# config/teams/messaging-policies.yaml
# Reference: https://learn.microsoft.com/en-us/graph/utcm-teams-resources#messagingpolicy-resource-type

resources:
  - resourceType: microsoft.teams.messagingpolicy
    properties:
      Identity: Global
      DisplayName: "Global Messaging Policy"
      AllowGiphy: true
      AllowImmersiveReader: true
      AllowMemes: true
      AllowOwnerDeleteMessage: false
      AllowPriorityMessages: true
      AllowSmartCompose: true
      AllowSmartReply: true
      AllowStickers: true
      AllowUrlPreviews: true
      AllowUserChat: true
      AllowUserDeleteMessage: true
      AllowUserEditMessage: true
      GiphyRatingType: Moderate
      ReadReceiptsEnabledType: UserOverride
