# config/entra/authorization-policy.yaml
# Controls what default users can do: create apps, create tenants, invite guests, etc.
# Reference: https://learn.microsoft.com/en-us/graph/utcm-entra-resources#authorizationpolicy-resource-type

resources:
  - resourceType: microsoft.entra.authorizationpolicy
    properties:
      IsSingleInstance: "Yes"
      Ensure: "Present"
